blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/shogo4405/HaishinKit.swift/discussions
    about: Please ask and answer questions here with *Q&A*
  - name: Feature request
    url: https://github.com/shogo4405/HaishinKit.swift/discussions
    about: You'd like to discuss a feature request here with *Idea*.
